import { useEffect } from 'react'
import Head from 'next/head'
import { Hero, Navbar, Gallery, Footer } from '@/components'
import { useAppDispatch } from '@/redux/store/reduxHooks'
import { resetUserState } from '@/redux/slices/userSlice'

export default function Home() {
  const dispatch = useAppDispatch()
  dispatch(resetUserState())

  return (
    <>
      <Head>
        <title>Curry Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <Gallery />
      <Footer />
    </>
  )
}
