import Head from 'next/head'
import { Hero, Navbar, Gallery } from '@/components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Curry Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <Gallery />
    </>
  )
}
